name: Projections

on:
  push:
    branches:
      - master

jobs:
  holobranch-projections:
    runs-on: ubuntu-latest
    steps:
    - name: Initialize Chef Habitat artifacts cache directory
      run: |
        sudo mkdir -p /hab/cache/artifacts
        sudo chown runner:docker -R /hab
    - name: Cache Chef Habitat artifacts
      uses: actions/cache@v1
      with:
        path: /hab/cache/artifacts
        key: hab-cache-artifacts
    - name: 'Update: cfc-staging-v3.poplar.phl.io'
      env:
        VFS_DEV_TOKEN: ${{ secrets.VFS_DEV_TOKEN }}
      run: |
        # pull latest commit
        curl -X POST \
          --silent \
          --fail \
          --show-error \
          -H "Authorization: Token ${VFS_DEV_TOKEN}" \
          -H "Accept: application/json" \
          "http://cfc-staging-v3.poplar.phl.io/site-admin/sources/codeforcroatia/pull?fetch=true" \
          | jq '.'

        # sync VFS to git
        curl -X POST \
          --silent \
          --fail \
          --show-error \
          -H "Authorization: Token ${VFS_DEV_TOKEN}" \
          -H "Accept: application/json" \
          "http://cfc-staging-v3.poplar.phl.io/site-admin/sources/codeforcroatia/sync-to-vfs" \
          | jq '.'
